# Gradle Options
org.gradle.jvmargs=-Xmx8G
org.gradle.daemon=false

# Project
mod_version=26.1-r1.2
project_group=net.rebel459.combat_reborn
license=Legacy License
java_version=25

# Mod
mod_author=Rebel459
mod_id=combat_reborn
mod_name=Combat Reborn
mod_description=A comprehensive combat update featuring overhauled shield mechanics, all-new quivers, reworked hunger systems, rebalanced weapon values and so much more.

# Minecraft
minecraft_version=26.1
neo_form_version=26.1-1

# Fabric
fabric_loader=0.18.5
fabric_api=0.145.1+26.1
fabric_minecraft_version=>=26.1 <26.2

# NeoForge
neoforge_version=26.1.0.19-beta
neoforge_minecraft_version=[26.1, 26.2)

# Common Dependencies
unified_version=26.1-r3.1
cloth_version=26.1.154

lal_version=26.1-r1.2
tooltips_version=26.1-r2.1
patcher_version=2.0-mc26.1
lithostitched_version = 1.6.8

# Fabric Dependencies
modmenu_version=18.0.0-alpha.8